//  v4: one of three interchangeable aes_sbox backends (see aes_sbox.sv's
//  header comment and aes_sbox_pkg.sv). This one is the minimum-area,
//  minimum-read-port option: a single logical 512x8 ROM (0x000-0x0ff
//  forward, 0x100-0x1ff inverse -- see rtl/aes_sbox_512.mem, generated by
//  scripts/gen_aes_sbox_mem.py from the same FIPS-197 table this module's
//  content is descended from) read one byte at a time, so a 32-bit word
//  substitution takes 4 cycles. Reference: the table values themselves are
//  unmodified from secworks/aes (see https://github.com/secworks/aesaes);
//  everything else here (the ROM, the byte-serial controller, the req/rsp
//  handshake) is new for v4.

//======================================================================
//
// aes_sbox_serial_rom.sv
// ----------------------
// AES S-box / inverse S-box, serialized: one 512x8 ROM, one address per
// cycle, four cycles to substitute a 32-bit word (4 independent bytes).
//
//
// Author: Joachim Strombergson (original table values)
// Copyright (c) 2013, 2014, Secworks Sweden AB
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or
// without modification, are permitted provided that the following
// conditions are met:
//
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in
//    the documentation and/or other materials provided with the
//    distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
// FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
// COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//======================================================================

`default_nettype none

// Default assumes the simulation's CWD is testbench/ (true for every
// existing `make` target in this repo, which always runs
// ./_build/<target>/V* from within testbench/) -- override with
// +define+AES_SBOX_MEM_PATH=\"...\" if that ever changes.
`ifndef AES_SBOX_MEM_PATH
  `define AES_SBOX_MEM_PATH "../rtl/aes_sbox_512.mem"
`endif

module aes_sbox_serial_rom (
                             input  wire        clk,
                             input  wire        reset_n,

                             input  wire        req_valid,
                             output wire        req_ready,
                             input  wire        inv,
                             input  wire [31:0] sboxw,

                             output wire        rsp_valid,
                             input  wire        rsp_ready,
                             output wire [31:0] new_sboxw
                            );

  //----------------------------------------------------------------
  // Controller states -- one per row of the spec's timing table:
  // ST_Bn means "rom_data holds byte n's result this cycle".
  //----------------------------------------------------------------
  localparam [2:0] ST_IDLE = 3'd0;  // req_ready=1, waiting for a request
  localparam [2:0] ST_B0   = 3'd1;  // capture byte0, issue addr for byte1
  localparam [2:0] ST_B1   = 3'd2;  // capture byte1, issue addr for byte2
  localparam [2:0] ST_B2   = 3'd3;  // capture byte2, issue addr for byte3
  localparam [2:0] ST_B3   = 3'd4;  // capture byte3, no more addresses to issue
  localparam [2:0] ST_RESP = 3'd5;  // rsp_valid held until rsp_ready

  //----------------------------------------------------------------
  // Registers.
  //----------------------------------------------------------------
  reg [2:0]  st_q,          st_new;
  reg        st_we;

  reg [31:0] input_word_q,  input_word_new;
  reg        inv_q,         inv_new;
  reg        input_we;

  reg [31:0] result_q,      result_new;
  reg        result_we;

  //----------------------------------------------------------------
  // The logical 512x8 ROM: one address, one registered byte out.
  //----------------------------------------------------------------
  reg [7:0] rom [0:511];
  reg [8:0] rom_addr;
  reg [7:0] rom_data;

  initial $readmemh(`AES_SBOX_MEM_PATH, rom);

  always @(posedge clk)
    rom_data <= rom[rom_addr];

  //----------------------------------------------------------------
  // Concurrent assignments for ports.
  //----------------------------------------------------------------
  assign req_ready = (st_q == ST_IDLE);
  // ST_B3 is the 4th ROM access -- its result (rom_data) is already valid
  // that same cycle, but result_q (the committed register) only catches
  // up on the edge leaving ST_B3. Forward rom_data directly for byte 3
  // while still in ST_B3 so rsp_valid can assert that same cycle (exactly
  // 4 cycles total, per the module header's timing table) without ever
  // exposing a stale (byte-3-missing) result alongside rsp_valid=1.
  // ST_RESP (reached only if the response had to be held past ST_B3, i.e.
  // rsp_ready was low) reads the now-fully-committed result_q instead.
  assign rsp_valid = (st_q == ST_B3) || (st_q == ST_RESP);
  assign new_sboxw = (st_q == ST_B3) ? {result_q[31 : 08], rom_data} : result_q;

  //----------------------------------------------------------------
  // sel_byte
  //
  // Picks byte `idx` (0=MSB..3=LSB) out of a 32-bit word -- same word
  // order every other consumer in this design already uses.
  //----------------------------------------------------------------
  function automatic [7 : 0] sel_byte(input [31 : 0] w, input [1 : 0] idx);
    begin
      case (idx)
        2'd0:    sel_byte = w[31 : 24];
        2'd1:    sel_byte = w[23 : 16];
        2'd2:    sel_byte = w[15 : 08];
        default: sel_byte = w[07 : 00];
      endcase
    end
  endfunction

  //----------------------------------------------------------------
  // ctrl
  //
  // Walks byte0..byte3 one ROM access at a time, per the module header's
  // timing table.
  //----------------------------------------------------------------
  always @*
    begin : ctrl
      st_new         = st_q;
      st_we          = 1'b0;
      input_word_new = input_word_q;
      inv_new        = inv_q;
      input_we       = 1'b0;
      result_new     = result_q;
      result_we      = 1'b0;
      rom_addr       = 9'h0;

      case (st_q)
        ST_IDLE:
          begin
            if (req_valid)
              begin
                input_word_new = sboxw;
                inv_new        = inv;
                input_we       = 1'b1;
                rom_addr       = {inv, sel_byte(sboxw, 2'd0)};
                st_new         = ST_B0;
                st_we          = 1'b1;
              end
          end

        ST_B0:
          begin
            result_new[31 : 24] = rom_data;
            result_we            = 1'b1;
            rom_addr             = {inv_q, sel_byte(input_word_q, 2'd1)};
            st_new               = ST_B1;
            st_we                = 1'b1;
          end

        ST_B1:
          begin
            result_new[23 : 16] = rom_data;
            result_we            = 1'b1;
            rom_addr             = {inv_q, sel_byte(input_word_q, 2'd2)};
            st_new               = ST_B2;
            st_we                = 1'b1;
          end

        ST_B2:
          begin
            result_new[15 : 08] = rom_data;
            result_we            = 1'b1;
            rom_addr             = {inv_q, sel_byte(input_word_q, 2'd3)};
            st_new               = ST_B3;
            st_we                = 1'b1;
          end

        ST_B3:
          begin
            // rsp_valid is already asserted this cycle (see the rsp_valid/
            // new_sboxw assigns above) -- if the caller can consume it
            // immediately (rsp_ready), skip ST_RESP entirely and go
            // straight back to idle; otherwise hold in ST_RESP until it's
            // consumed. Either way, result_q still gets byte 3 committed
            // here so ST_RESP's own (non-bypassed) read is correct.
            result_new[07 : 00] = rom_data;
            result_we            = 1'b1;
            st_we                = 1'b1;
            if (rsp_ready)
              st_new = ST_IDLE;
            else
              st_new = ST_RESP;
          end

        ST_RESP:
          begin
            if (rsp_ready)
              begin
                st_new = ST_IDLE;
                st_we  = 1'b1;
              end
          end

        default:
          begin
            st_new = ST_IDLE;
            st_we  = 1'b1;
          end
      endcase
    end // ctrl

  //----------------------------------------------------------------
  // reg_update
  //----------------------------------------------------------------
  always @ (posedge clk or negedge reset_n)
    begin : reg_update
      if (!reset_n)
        begin
          st_q         <= ST_IDLE;
          input_word_q <= 32'h0;
          inv_q        <= 1'b0;
          result_q     <= 32'h0;
        end
      else
        begin
          if (st_we)
            st_q <= st_new;

          if (input_we)
            begin
              input_word_q <= input_word_new;
              inv_q        <= inv_new;
            end

          if (result_we)
            result_q <= result_new;
        end
    end // reg_update

endmodule // aes_sbox_serial_rom

//======================================================================
// EOF aes_sbox_serial_rom.sv
//======================================================================
