///////////////////////////////////////////////////////////////////////////////////////
// Auto-generated by tools/gen_static_test.py -- DO NOT EDIT BY HAND
// Static (no file I/O) KAT test for ML-DSA-2
///////////////////////////////////////////////////////////////////////////////////////

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "api.h"
#include "params.h"
#include "sign.h"
#include "test_vectors_2.h"
#ifndef PERF_CNT_CYCLES
#define PERF_CNT_CYCLES 1
#endif

#if PERF_CNT_CYCLES
#include "encoding.h"
#endif /* PERF_CNT_CYCLES */

#if PERF_CNT_CYCLES
#endif /* PERF_CNT_CYCLES */

#define RUN_KEYGEN  1
#define RUN_SIGN    1
#define RUN_VERIFY  1

int main(void)
{
#if PERF_CNT_CYCLES
    unsigned long cycles, instrs;
    clear_csr(mcountinhibit, 0x5); /* bit0=CY (mcycle), bit2=IR (minstret) */
#endif /* PERF_CNT_CYCLES */

    uint8_t sk[CRYPTO_SECRETKEYBYTES];
    uint8_t pk[CRYPTO_PUBLICKEYBYTES];

    uint8_t m[MLEN_KAT];
    uint8_t sm[MLEN_KAT + CRYPTO_BYTES];
    uint8_t m1[MLEN_KAT + CRYPTO_BYTES];

    uint8_t seed_keygen[SEEDBYTES];
    uint8_t seed_sign[RNDBYTES];

    size_t smlen = SMLEN_KAT, mlen1;
    int fails = 0;

    for (int i = 0; i < N_KAT; i++) {
        printf("=== KAT %d/%d ===\n", i + 1, N_KAT);
        memcpy(m, TVEC_IN_M_SIGN[i], MLEN_KAT);

#if RUN_KEYGEN
        memcpy(seed_keygen, TVEC_SEED_IN_KEYPAIR[i], SEEDBYTES);
        #if PERF_CNT_CYCLES
        write_csr(mcycle, 0);
        write_csr(minstret, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_sign_keypair(pk, sk, seed_keygen);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        instrs = read_csr(minstret);
        printf("[%d] cycles crypto_sign_keypair: %lu\n", i, cycles);
        printf("[%d] instructions crypto_sign_keypair: %lu\n", i, instrs);
        #endif /* PERF_CNT_CYCLES */
        if (memcmp(pk, TVEC_OUT_PK[i], CRYPTO_PUBLICKEYBYTES)) { printf("[%d] ERROR: PK mismatch\n", i); fails++; }
        if (memcmp(sk, TVEC_OUT_SK[i], CRYPTO_SECRETKEYBYTES)) { printf("[%d] ERROR: SK mismatch\n", i); fails++; }
#else
        memcpy(pk, TVEC_OUT_PK[i], CRYPTO_PUBLICKEYBYTES);
        memcpy(sk, TVEC_OUT_SK[i], CRYPTO_SECRETKEYBYTES);
#endif /* RUN_KEYGEN */

#if RUN_SIGN
        memcpy(seed_sign, TVEC_SEED_IN_SIGN[i], RNDBYTES);
        #if PERF_CNT_CYCLES
        write_csr(mcycle, 0);
        write_csr(minstret, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_sign(sm, &smlen, m, MLEN_KAT, NULL, 0, sk, seed_sign);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        instrs = read_csr(minstret);
        printf("[%d] cycles crypto_sign: %lu\n", i, cycles);
        printf("[%d] instructions crypto_sign: %lu\n", i, instrs);
        #endif /* PERF_CNT_CYCLES */
        if (smlen != SMLEN_KAT || memcmp(sm, TVEC_IN_SM_SIGN[i], SMLEN_KAT)) { printf("[%d] ERROR: SM mismatch\n", i); fails++; }
#else
        memcpy(sm, TVEC_IN_SM_SIGN[i], SMLEN_KAT);
        smlen = SMLEN_KAT;
#endif /* RUN_SIGN */

#if RUN_VERIFY
        #if PERF_CNT_CYCLES
        write_csr(mcycle, 0);
        write_csr(minstret, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_sign_open(m1, &mlen1, sm, SMLEN_KAT, NULL, 0, pk);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        instrs = read_csr(minstret);
        printf("[%d] cycles crypto_sign_open: %lu\n", i, cycles);
        printf("[%d] instructions crypto_sign_open: %lu\n", i, instrs);
        #endif /* PERF_CNT_CYCLES */
        if (mlen1 != MLEN_KAT || memcmp(m1, TVEC_IN_M_SIGN[i], MLEN_KAT)) { printf("[%d] ERROR: M mismatch\n", i); fails++; }
#endif /* RUN_VERIFY */
    }

    if (fails == 0) {
        printf("Test Successful (%d KAT vector(s))\n", N_KAT);
    } else {
        printf("Test FAILED: %d mismatch(es)\n", fails);
    }

    return fails != 0;
}
