# Out-of-context synthesis of the CVA6 core + HASH_IP coprocessor only
# (no SoC peripherals, no MIG, no JTAG, no UART, no IPs).
#
# Required env vars:
#   XILINX_PART     : Vivado part to target (e.g. xc7a100tftg256-2)
#   CLK_PERIOD_NS   : Target clock period in ns for the core clk_i
#   SRC_LIST_TCL    : Path to the generated tcl file with `read_verilog -sv {...}`
#                     lines listing the source files
#   CORE_TOP        : Top module to synthesize (defaults to "ariane")

set part        $::env(XILINX_PART)
set clk_period  $::env(CLK_PERIOD_NS)
set src_tcl     $::env(SRC_LIST_TCL)
if {[info exists ::env(CORE_TOP)]} {
  set top $::env(CORE_TOP)
} else {
  set top "ariane"
}

set work_dir "work-fpga-core"
file mkdir $work_dir
file mkdir reports_core

# In-memory project for out-of-context synthesis
create_project -in_memory -part $part synth_core

# Include directories (same as full FPGA flow)
set_property include_dirs [list \
    "src/axi_sd_bridge/include" \
    "../../vendor/pulp-platform/common_cells/include" \
    "../../vendor/pulp-platform/axi/include" \
    "../../core/cache_subsystem/hpdcache/rtl/include" \
    "../register_interface/include" \
    "../instr_tracing/ITI/include" \
    "../../core/include" \
] [current_fileset]

# Header files that must be flagged as global include
set headers [list \
    "../../vendor/pulp-platform/common_cells/include/common_cells/registers.svh" \
]
read_verilog -sv $headers
set hdr_obj [get_files -of_objects [get_filesets sources_1] $headers]
set_property -dict { file_type {Verilog Header} is_global_include 1 } -objects $hdr_obj

# Read all source files (packages first, generated by the Makefile)
source $src_tcl

set_property top $top [current_fileset]
update_compile_order -fileset sources_1

# Out-of-context constraints: just a single virtual clock on clk_i
set xdc_file "$work_dir/ooc_synth.xdc"
set fp [open $xdc_file "w"]
puts $fp "create_clock -name clk_i -period $clk_period \[get_ports clk_i\]"
close $fp
read_xdc $xdc_file

# Synthesize out-of-context (no I/O buffers inserted)
synth_design -top $top -part $part -mode out_of_context

# Save checkpoint and reports
write_checkpoint -force $work_dir/${top}_synth.dcp
report_utilization -hierarchical -file reports_core/${top}.utilization.rpt
report_timing_summary            -file reports_core/${top}.timing_summary.rpt
report_timing -max_paths 100 -nworst 100 -delay_type max -sort_by slack \
                                 -file reports_core/${top}.timing_WORST_100.rpt
report_design_analysis           -file reports_core/${top}.design_analysis.rpt
puts "\[SYNTH-CORE\] Done. Checkpoint: $work_dir/${top}_synth.dcp"
