///////////////////////////////////////////////////////////////////////////////////////
// Auto-generated by tools/gen_static_test.py -- DO NOT EDIT BY HAND
// Static (no file I/O) KAT test for FAEST_EM_256S
//
// NOTE: this family has no explicit-randomness ("derand") entry point --
// determinism comes from reseeding its internal CSPRNG/DRBG with the
// captured `seed` before each keygen+sign pair, exactly like
// kat/gen/main_{cross,less,hawk,faest}.c does for the dynamic KAT test.
// crypto_sign_keypair() is always called (even with RUN_KEYGEN=0) purely to
// advance that stream to the position sign() expects.
///////////////////////////////////////////////////////////////////////////////////////

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "rng.h"
#include "api.h"
#include "test_vectors_EM_256S.h"

#define PERF_CNT_CYCLES 1

#if PERF_CNT_CYCLES
#include "inc/uart.h"
#include "encoding.h"
#endif /* PERF_CNT_CYCLES */

#define RUN_KEYGEN  1
#define RUN_SIGN    1
#define RUN_VERIFY  1

int main(void)
{
#if PERF_CNT_CYCLES
    int cycles;
    clear_csr(mcountinhibit, 1);
#endif /* PERF_CNT_CYCLES */

    uint8_t pk[CRYPTO_PUBLICKEYBYTES];
    uint8_t sk[CRYPTO_SECRETKEYBYTES];
    uint8_t m[MLEN_KAT];
    uint8_t sm[MLEN_KAT + CRYPTO_BYTES];
    uint8_t m1[MLEN_KAT + CRYPTO_BYTES];
    unsigned long long smlen, mlen1;
    int fails = 0;

    for (int i = 0; i < N_KAT; i++) {
        printf("=== KAT %d/%d ===\n", i + 1, N_KAT);
        memcpy(m, TVEC_IN_M_SIGN[i], MLEN_KAT);

        randombytes_init(TVEC_SEED[i], NULL, 256);
        { uint8_t _skip[MLEN_KAT]; randombytes(_skip, MLEN_KAT); } /* advance past the msg draw the generator made before keygen */

        /* always called: advances the shared CSPRNG/DRBG stream so sign() lines up */
        #if PERF_CNT_CYCLES
        printf("-- keygen --\n");
        write_csr(mcycle, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_sign_keypair(pk, sk);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        printf("Cycles: %d\n", cycles);
        #endif /* PERF_CNT_CYCLES */
#if RUN_KEYGEN
        if (memcmp(pk, TVEC_OUT_PK[i], CRYPTO_PUBLICKEYBYTES)) { printf("[%d] ERROR: PK mismatch\n", i); fails++; }
        if (memcmp(sk, TVEC_OUT_SK[i], CRYPTO_SECRETKEYBYTES)) { printf("[%d] ERROR: SK mismatch\n", i); fails++; }
#else
        memcpy(pk, TVEC_OUT_PK[i], CRYPTO_PUBLICKEYBYTES);
        memcpy(sk, TVEC_OUT_SK[i], CRYPTO_SECRETKEYBYTES);
#endif /* RUN_KEYGEN */

#if RUN_SIGN
        #if PERF_CNT_CYCLES
        printf("-- sign --\n");
        write_csr(mcycle, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_sign(sm, &smlen, m, MLEN_KAT, sk);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        printf("Cycles: %d\n", cycles);
        #endif /* PERF_CNT_CYCLES */
        if (smlen != TVEC_IN_SM_SIGN_LEN[i] || memcmp(sm, TVEC_IN_SM_SIGN[i], TVEC_IN_SM_SIGN_LEN[i])) {
            printf("[%d] ERROR: SM mismatch\n", i); fails++;
        }
#else
        memcpy(sm, TVEC_IN_SM_SIGN[i], TVEC_IN_SM_SIGN_LEN[i]);
        smlen = TVEC_IN_SM_SIGN_LEN[i];
#endif /* RUN_SIGN */

#if RUN_VERIFY
        #if PERF_CNT_CYCLES
        printf("-- verify --\n");
        write_csr(mcycle, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_sign_open(m1, &mlen1, sm, smlen, pk);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        printf("Cycles: %d\n", cycles);
        #endif /* PERF_CNT_CYCLES */
        if (mlen1 != MLEN_KAT || memcmp(m1, TVEC_IN_M_SIGN[i], MLEN_KAT)) { printf("[%d] ERROR: M mismatch\n", i); fails++; }
#endif /* RUN_VERIFY */
    }

    if (fails == 0) {
        printf("Test Successful (%d KAT vector(s))\n", N_KAT);
    } else {
        printf("Test FAILED: %d mismatch(es)\n", fails);
    }

    return fails != 0;
}
