///////////////////////////////////////////////////////////////////////////////////////
// Auto-generated by tools/gen_static_test.py -- DO NOT EDIT BY HAND
// Static (no file I/O) KAT test for ml-kem-768
///////////////////////////////////////////////////////////////////////////////////////

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <inttypes.h>

#include "kem.h"
#include "test_vectors_768.h"
#ifndef PERF_CNT_CYCLES
#define PERF_CNT_CYCLES 1
#endif

#if PERF_CNT_CYCLES
#include "encoding.h"
#endif /* PERF_CNT_CYCLES */

#if PERF_CNT_CYCLES
#endif /* PERF_CNT_CYCLES */

#define RUN_KEYGEN  1
#define RUN_ENCAPS  1
#define RUN_DECAPS  1

static uint8_t pk[KYBER_PUBLICKEYBYTES];
static uint8_t sk[KYBER_SECRETKEYBYTES];
static uint8_t ct[KYBER_CIPHERTEXTBYTES];
static uint8_t key_a[KYBER_SSBYTES];
static uint8_t key_b[KYBER_SSBYTES];

int main(void)
{
#if PERF_CNT_CYCLES
    unsigned long cycles, instrs;
    clear_csr(mcountinhibit, 0x5); /* bit0=CY (mcycle), bit2=IR (minstret) */
#endif /* PERF_CNT_CYCLES */

    int fails = 0;

    for (int i = 0; i < N_KAT; i++) {
        printf("=== KAT %d/%d ===\n", i + 1, N_KAT);

#if RUN_KEYGEN
        #if PERF_CNT_CYCLES
        write_csr(mcycle, 0);
        write_csr(minstret, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_kem_keypair_derand(pk, sk, TVEC_IN_KEM_KEYPAIR[i]);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        instrs = read_csr(minstret);
        printf("[%d] cycles crypto_kem_keypair_derand: %lu\n", i, cycles);
        printf("[%d] instructions crypto_kem_keypair_derand: %lu\n", i, instrs);
        #endif /* PERF_CNT_CYCLES */
        if (memcmp(pk, TVEC_OUT_PK[i], KYBER_PUBLICKEYBYTES)) { printf("[%d] ERROR: PK mismatch\n", i); fails++; }
        if (memcmp(sk, TVEC_OUT_SK[i], KYBER_SECRETKEYBYTES)) { printf("[%d] ERROR: SK mismatch\n", i); fails++; }
#else
        memcpy(pk, TVEC_OUT_PK[i], KYBER_PUBLICKEYBYTES);
        memcpy(sk, TVEC_OUT_SK[i], KYBER_SECRETKEYBYTES);
#endif /* RUN_KEYGEN */

#if RUN_ENCAPS
        #if PERF_CNT_CYCLES
        write_csr(mcycle, 0);
        write_csr(minstret, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_kem_enc_derand(ct, key_b, pk, TVEC_IN_KEM_ENC[i]);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        instrs = read_csr(minstret);
        printf("[%d] cycles crypto_kem_enc_derand: %lu\n", i, cycles);
        printf("[%d] instructions crypto_kem_enc_derand: %lu\n", i, instrs);
        #endif /* PERF_CNT_CYCLES */
        if (memcmp(ct, TVEC_OUT_CT[i], KYBER_CIPHERTEXTBYTES)) { printf("[%d] ERROR: CT mismatch\n", i); fails++; }
        if (memcmp(key_b, TVEC_OUT_SS[i], KYBER_SSBYTES)) { printf("[%d] ERROR: SS(enc) mismatch\n", i); fails++; }
#else
        memcpy(ct, TVEC_OUT_CT[i], KYBER_CIPHERTEXTBYTES);
        memcpy(key_b, TVEC_OUT_SS[i], KYBER_SSBYTES);
#endif /* RUN_ENCAPS */

#if RUN_DECAPS
        #if PERF_CNT_CYCLES
        write_csr(mcycle, 0);
        write_csr(minstret, 0);
        #endif /* PERF_CNT_CYCLES */
        crypto_kem_dec(key_a, ct, sk);
        #if PERF_CNT_CYCLES
        cycles = read_csr(mcycle);
        instrs = read_csr(minstret);
        printf("[%d] cycles crypto_kem_dec: %lu\n", i, cycles);
        printf("[%d] instructions crypto_kem_dec: %lu\n", i, instrs);
        #endif /* PERF_CNT_CYCLES */
        if (memcmp(key_a, TVEC_OUT_SS[i], KYBER_SSBYTES)) { printf("[%d] ERROR: SS(dec) mismatch\n", i); fails++; }
#endif /* RUN_DECAPS */
    }

    if (fails == 0) {
        printf("Test Successful (%d KAT vector(s))\n", N_KAT);
    } else {
        printf("Test FAILED: %d mismatch(es)\n", fails);
    }

    return fails != 0;
}
